import {
  Zap,
  Globe,
  Shield,
  Wifi,
  MessageCircle,
  RefreshCw,
  Search,
  ShoppingCart,
  QrCode,
  Check,
  ArrowRight,
  Phone,
  Mail,
  Lock,
  User,
  LogOut,
  Signal,
  Star,
  Download,
  Menu,
  X,
  Cpu,
  MapPin,
  Heart,
  Clock,
  Gift,
  Eye,
  EyeOff,
  Settings,
  Pencil,
  Copy,
  FileText,
  Trash2,
  AlertCircle,
  Loader2,
  Building2,
  CreditCard,
  Wallet,
  ChevronRight,
  Sun,
  Moon,
  Languages,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  bolt: Zap,
  zap: Zap,
  globe: Globe,
  shield: Shield,
  wifi: Wifi,
  chat: MessageCircle,
  refresh: RefreshCw,
  search: Search,
  cart: ShoppingCart,
  qr: QrCode,
  check: Check,
  arrow: ArrowRight,
  chevron: ChevronRight,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  user: User,
  logout: LogOut,
  signal: Signal,
  star: Star,
  download: Download,
  menu: Menu,
  x: X,
  sim: Cpu,
  map: MapPin,
  heart: Heart,
  clock: Clock,
  gift: Gift,
  eye: Eye,
  eyeOff: EyeOff,
  settings: Settings,
  edit: Pencil,
  copy: Copy,
  doc: FileText,
  trash: Trash2,
  alert: AlertCircle,
  loader: Loader2,
  bank: Building2,
  card: CreditCard,
  wallet: Wallet,
  sun: Sun,
  moon: Moon,
  lang: Languages,
};

type IconProps = {
  name: string;
  className?: string;
};

export default function Icon({ name, className = "w-5 h-5" }: IconProps) {
  const Cmp = map[name] ?? Search;
  return <Cmp className={className} aria-hidden="true" />;
}
